{
 "title": "N8N Leads",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Prometheus Source", "query": "prometheus" },
   { "name": "pg_datasource", "label": "PostgreSQL Source", "query": "postgres" }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Leads Históricos",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT count(*) FROM leads;" }
   ]
  },
  {
   "title": "Leads por Fuente (Source)",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 10, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "leads_db",
     "rawSql": "SELECT source, COUNT(id) FROM leads GROUP BY source ORDER BY COUNT(id) ASC "
    }
   ]
  },
  {
   "title": "Distribución por Estado",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "leads_db",
     "rawSql": "SELECT status, COUNT(id) FROM leads GROUP BY status LIMIT 50 "
    }
   ]
  },
  {
   "title": "Leads en Error (Total Histórico)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "leads_db",
     "rawSql": "SELECT COUNT(*) FROM leads WHERE status = 'error' LIMIT 50 "
    }
   ]
  },
  {
   "title": "Leads Recibidos (Últimas 24h)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at, 1m),\n  count(id) AS \"leads\"\nFROM leads\nWHERE\n  $__timeFilter(created_at)\nGROUP BY 1\nORDER BY 1;"
    }
   ]
  },
  { "title": "RENDIMIENTO DEL PIPELINE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Evolución de  Estado por minuto",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroupAlias(created_at, 1m), count(*) AS value, status FROM leads WHERE $__timeFilter(created_at) GROUP BY 3,1 ORDER BY 1"
    }
   ]
  },
  {
   "title": "LOG DE ERRORES CRÍTICOS (SQL)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Últimos Errores Registrados en Base de Datos",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
     "targets": [
      {
       "rawSql": "SELECT created_at AS \"Fecha\", workflow_name AS \"Workflow\", error_message AS \"Error\", node_name AS \"Nodo\" FROM workflow_error_log ORDER BY created_at DESC LIMIT 10;"
      }
     ]
    }
   ]
  }
 ]
}